import com.optimizely.ab.Optimizely
import com.optimizely.ab.OptimizelyFactory

fun main() {
    val optimizely = buildOptimizely()
// ℹ️ After the code is generated by poetimizely, all of this will be possible:
//    optimizely.getAllExperiments().forEach(::println)
//    optimizely.isFeatureEnabled(Features.EXAMPLE_FEATURE, userId)
//    optimizely.getVariationForExperiment(Experiments.ExampleExperiment, userId)
}

private fun buildOptimizely(): Optimizely =
    OptimizelyFactory.newDefaultInstance(System.getenv("OPTIMIZELY_SDK_KEY"))
