name: release

on:
  push:
    branches: [ master ]
    paths:
    - 'poetimizely.properties'

jobs:
  publish_plugin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set LOCAL_MAVEN_URL environment variable
      run: echo ::set-env name=LOCAL_MAVEN_URL::$(echo $GITHUB_WORKSPACE/repository)

    - name: Build and publish generator in local Maven repository
      run: ./generator/gradlew -p=generator publish

    # Publish the plugin to Gradle Plugin Portal (key and secret are stored as secrets in the repo)
    - name: Publish the plugin in Gradle Plugin Portal
      run: ./gradle-plugin/gradlew -p=gradle-plugin publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

    - name: Set plugin version in an environment variable
      run: echo ::set-env name=PLUGIN_VERSION::$(cat poetimizely.properties | grep "version" | cut -d'=' -f2-)

    - name: Create and push the Git tag
      run: git tag $PLUGIN_VERSION && git push origin $PLUGIN_VERSION

    - name: Create GitHub release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.PLUGIN_VERSION }}
        release_name: ${{ env.PLUGIN_VERSION }}
        body: https://plugins.gradle.org/plugin/com.patxi.poetimizely/${{ env.PLUGIN_VERSION }}