name: release

on:
  push:
    tags:
      - v*

jobs:
  publish_plugin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Set tag version in an environment variable (remove the first character)
      run: echo ::set-env name=NEW_VERSION::$(echo ${{ github.event.release.tag_name }} | cut -c 2-)

    - name: Set generator version in an environment variable
      run: echo ::set-env name=GENERATOR_VERSION::$(./gradlew properties | grep ^version:)
      working-directory: ./generator

    - name: Set gradle-plugin version in an environment variable
      run: echo ::set-env name=GRADLE_PLUGIN_VERSION::$(./gradlew properties | grep ^version:)
      working-directory: ./gradle-plugin

    - name: Set maven-plugin version in an environment variable
      run: echo ::set-env name=MAVEN_PLUGIN_VERSION::$(./mvnw org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
      working-directory: ./maven-plugin

    - name: Check if there is a version mismatch between generator, gradle-plugin and maven-plugin
      if: $GENERATOR_VERSION != $NEW_VERSION || $GRADLE_PLUGIN_VERSION != $NEW_VERSION || $MAVEN_PLUGIN_VERSION != $NEW_VERSION
      run: exit 1

    - name: Build and publish generator in local Maven repository
      run: ./gradlew publishToMavenLocal
      working-directory: ./generator

    - name: Build and publish generator in JCenter
      run: ./gradlew bintrayUpload
      working-directory: ./generator
      env:
        BINTRAY_API_USER: ${{ secrets.BINTRAY_API_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

    - name: Build and publish the Maven plugin in JCenter
      run: ./mvnw deploy --settings=settings.xml
      working-directory: ./maven-plugin
      env:
        BINTRAY_API_USER: ${{ secrets.BINTRAY_API_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

    - name: Build and publish the Gradle plugin in Gradle Plugin Portal
      run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
      working-directory: ./gradle-plugin

    - name: Create GitHub release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.NEW_VERSION }}
        release_name: ${{ env.NEW_VERSION }}
        body: |
          https://plugins.gradle.org/plugin/com.patxi.poetimizely/${{ env.GRADLE_PLUGIN_VERSION }}
          https://bintray.com/patxibocos/com.patxi/poetimizely-generator/${{ env.GENERATOR_VERSION }}
          https://bintray.com/patxibocos/com.patxi/poetimizely-maven-plugin/${{ env.MAVEN_PLUGIN_VERSION }}